#include <pgetopt-4.2/pgetopt.h>

#include <stdio.h> // just for printf :)

int main ( int argc, char **argv )
{
    pinit *init = pinit_create ();
    
    pclass *class = pclass_create ( init, "main" );
    
    pinit_set_main_class ( init, class );

    palw main_allowed_options [] = {
        { 1, "long_flag" },
        { 2, "f" },
        EOL
    };

    pclass_set_allowed_options ( class, main_allowed_options );

    usrerr _error = pinit_parser ( init, argc, argv ); // As its name suggests, this function performs part of the parsing operation.
    /* Specifically, this function initializes (or populates) the PAVl structure with the values consisting 
       of the arguments entered by the user.
     * usrerr is a simple two-part structure consisting of an error index and an error type. The error message is handled and generated by 
       the usererror_parser function, but you can do this manually. For more information, see the document manual.
    */

    if ( usererror_parser ( _error, argv ) ) return -1; // This function will issue the appropriate error type based on the value of the usrerr variable you defined.

    {
        int opt_id, i=0;
        
        while ( ( opt_id = pclass_loop_get_opt_id ( class, i ) ) != -1 ) {
            switch ( opt_id )
            {
                case (1):
                    printf ("this is long_flag\n");
                    break;
                case (2):
                    printf ("this is f\n");
                    break;
            }
            ++i;
        }
    }
    
    pclass_free (class);
    pinit_free (init);
}

/* Example Export :
 * If you provide no arguments to the software, you should see no output.

 $ ./example -f --long_flag
 this is f
 this is long_flag

 $ ./example -d
 Error: -d
 invalid option.
 
 $ ./example @mahdi.test
 Error: @mahdi.test
 There is no class under this name
 
*/